{"uuid": "7cb8431f-69a2-4557-8bf8-5a7928ee98e6", "children": ["542f2786-faab-43b5-a4da-6dbc324234cd"], "befores": [{"name": "cau_hinh", "status": "broken", "statusDetails": {"message": "requests.exceptions.ChunkedEncodingError: (\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))\n", "trace": "  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\Doan4\\codedoan4\\tests\\conftest.py\", line 37, in cau_hinh\n    service = Service(ChromeDriverManager().install())\n                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\chrome.py\", line 40, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 40, in _get_driver_binary_path\n    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\download_manager.py\", line 32, in download_file\n    return File(response, file_name)\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\file_manager.py\", line 12, in __init__\n    self.content = stream.content\n                   ^^^^^^^^^^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\requests\\models.py\", line 902, in content\n    self._content = b\"\".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b\"\"\n                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Doan4\\codedoan4\\.venv\\Lib\\site-packages\\requests\\models.py\", line 822, in generate\n    raise ChunkedEncodingError(e)\n"}, "start": 1760576119532, "stop": 1760576156090}], "start": 1760576119532, "stop": 1760576156804}